### ISSUE TITLE
Very good job. Which paper did you refer to？

### ISSUE THREAD

**Issue by XIANG07** [li-haojia/ellipse-fitting-kalman-filter#1]

**Comment by li-haojia** [comment]
> _No description provided._

Sorry for late reply.

I refer the paper named [_Real-time FPGA-based Kalman Filter for Constant and Non-constant Velocity Periodic Error Correction_](https://www.researchgate.net/publication/310813141_Real-time_FPGA-based_Kalman_Filter_for_Constant_and_Non-constant_Velocity_Periodic_Error_Correction).   

But in my opinion, this paper has some errors. I think this method should be Kalman filter in least squares, not the Extend  Kalman filter. I think we just use the linear model.

Some other examples that you can refer are  [here](https://blog.csdn.net/ktigerhero3/article/details/89308149) and [here](https://zhuanlan.zhihu.com/p/67250500)

**Comment by XIANG07** [comment]
Thanks! 
Best regards.
